# @escaping과 @autoclosure

클로저를 함수나 메소드의 인자값으로 사용할 때에는 용도에 따라 `@escaping`과 `@autoclosure`를 사용할 수 있어요.

### @escaping

`@escaping`은 함수나 메소드의 인자값으로 전달된 클로저가 함수나 메소드의 실행이 종료된 후에도 호출될 수 있음을 나타내는 키워드에요. 우선 다음 예제를 봐요.

```swift
func callback(fn: () -> Void) {
    fn()
}

callback {
    print("Closure가 실행되었습니다.")
}
```

위 예제는 함수의 인자값으로 클로저를 전달하고 있어요. 이번에는 이 코드를 다음과 같이 바꿔 볼게요.

```swift
func callback(fn: () -> Void) {
    let f = fn()
    f()
}
```

전달된 클로저를 우선 변수에 대입한 후에 실행하도록 과정을 추가했어요. 그런데 이를 실행하면 다음과 같은 오류가 발생해요.

> Non-escaping parameter 'fn' may only be called

오류의 내용은 Non-escaping 파라미터인 fn은 호출될 수 없다는 내용이에요. 어찌된 일일까요?

스위프트에서 함수의 인자값으로 전달된 클로저는 기본적으로 **탈출불가(non-escape)** 의 성격을 가져요. 이는 해당 클로저를 함수 내에서, 직접 실행을 위해서만 사용해야 하는 것을 의미하며, 이 때문에 함수 내부라 할지라도 변수나 상수에 대입할 수 없어요.

또한 동일한 의미에서 인자값으로 전달된 클로저는 중첩된 내부 함수에서 사용할 수도 없어요. 따라서 아래 예제를 실행하면 오류가 발생해요.

```swift
func callback(fn: () -> Void) {
    func nested() {
        fn()
    }
}
```

하지만 코드를 작성하다 보면 클로저를 변수나 상수에 대입하거나 중첩 함수 내부에서 사용해야할 경우도 있는데요, 이때 사용되는 것이 @escaping 키워드에요. 확인을 위해 조금 전에 정의한 callback(fn:) 함수의 매개변수 타입에 @escaping 키워드를 추가해 볼게요.

```swift
func callback(fn: @escaping () -> Void) {
    let f = fn()
    f()
}
```

이제는 클로저를 변수에 대입하고, 중첩 함수 내부에서도 사용할 수 있어요.

그렇다면 인자값으로 전달되는 클로저의 기본 속성이 탈출불가하도록 설정된 이유는 무엇일까요?

클로저의 기본 속성을 탈출불가하게 관리함으로써 얻어지는 가장 큰 이점은 컴파일러가 코드를 최적화하는 과정에서의 성능향상이에요. 해당 클로저가 탈출할 수 없다는 것은 컴파일러가 더 이상 메모리 관리상의 지저분한 일들에 관여할 필요없다는 뜻이기 때문이에요.

또한, 탈출 클로저 내에서는 self키워드를 사용할 수 있어요.

### @autoclosure

`@autoclosure`는 함수나 메소드의 인자값으로 전달되는 일반적인 표현식을 클로저로 변환해주는 키워드에요. 이 키워드는 함수나 메소드의 인자값으로 전달되는 표현식을 클로저로 감싸주는 역할을 해요.

```swift
func condition(stmt: () -> Bool) {
    if stmt() == true {
        print("결과가 참입니다.")
    } else {
        print("결과가 거짓입니다.")
    }
}
```

위 예제는 함수의 인자값으로 클로저를 전달받고 있어요. 이 함수를실행하고자 하는 경우, 다음의 두 가지 방법을 사용할 수 있었어요.

```swift
// 일반 구문
condition(stmt: { 3 > 5 })
// 클로저 구문
condition { 3 > 5 }
```

이번에는 @autoclosure 키워드를 사용하여 함수의 인자값으로 전달되는 표현식을 클로저로 감싸보겠어요.

```swift
func condition(stmt: @autoclosure () -> Bool) {
    if stmt() == true {
        print("결과가 참입니다.")
    } else {
        print("결과가 거짓입니다.")
    }
}
```

이제 @autoclosure 속성의 영향으로 더이상 일반 클로저를 인자값으로 사용할 수 없기 때문에 반드시 아래와 같은 형식으로 사용해야 해요.

```swift
condition(stmt: 3 > 5)
```

핵심은 하나에요. 클로저가 아니라 그 안에 들어가는 내용만 인자값으로 넣어줄 뿐이죠. 이렇게 @autoclosure 속성을 사용하면 함수나 메소드의 인자값으로 전달되는 표현식을 클로저로 감싸주는 과정을 생략할 수 있어요.

@autoclosure 속성과 관련하여 알아두어야 할 개념이 하나 있어요. 바로 '지연된 실행'이죠. 다음 예제를 보면서 지연된 실행에 대해 알아볼게요.

```swift
var arrs = [String]()

func addVars(fn: @autoclosure () -> Void) {
    arrs = Arraay(repeating: "", count: 3)
    fn()
}

// 오류가 발생해요.
arrs.insert("KR", at: 1)
```

문자열을 요소로 가지는 빈 배열 arrs를 정의했어요. 아직 초기화만 되어 있을 뿐 내용은 모두 비어 있는 상태로, addVars(fn:) 함수를 실행하면 배열의 크기가 3으로 늘어나고, 각 요소는 빈 문자열로 채워져요. 이 때문에 맨 마지막에 작성된 arrs.insert(at:) 메소드는 오류가 발생해요. addVars(fn:) 함수가 실행되지 않아서 인덱스가 그만큼 확장되어 있지 않기 때문이에요.

이제 아래에 다음과 같은 구문을 추가해 볼게요.

```swift
addVars(fn: arrs.insert("KR", at: 1))
```

신기하게도, 이 구문은 오류가 발생하지 않아요. 이것이 바로 **지연된 실행**이에요.

원래 구문은 작성하는 순간에 실행되는 것이 맞지만, 함수 내에 작성된 구문은 함수가 실행되기 전까지는 실행되지 않아요. @autoclosure 속성이 부여된 인자값은 보기엔 일반 구문 형태이지만 컴파일러에 의해 클로저, 즉 함수로 변환되어 처리되기 때문에 함수가 실행되기 전까지는 실행되지 않아요.

정리해보면, @autoclosure 속성은 함수나 메소드의 인자값으로 전달되는 표현식을 클로저로 감싸주는 역할을 해요. 또한, @autoclosure 속성이 부여된 인자값은 보기엔 일반 구문 형태이지만 컴파일러에 의해 클로저, 즉 함수로 변환되어 처리되기 때문에 함수가 실행되기 전까지는 실행되지 않아요.

[이전](https://github.com/MojitoBar/iOS-DeepDive/blob/main/%EA%BC%BC%EA%BC%BC%ED%95%9C_%EC%9E%AC%EC%9D%80%EC%94%A8%EC%9D%98_Swift_%EB%AC%B8%EB%B2%95%ED%8E%B8/7.4.3.md)
[다음](https://github.com/MojitoBar/iOS-DeepDive/blob/main/%EA%BC%BC%EA%BC%BC%ED%95%9C_%EC%9E%AC%EC%9D%80%EC%94%A8%EC%9D%98_Swift_%EB%AC%B8%EB%B2%95%ED%8E%B8/8.md)

[처음으로](https://github.com/MojitoBar/iOS-DeepDive/blob/main/%EA%BC%BC%EA%BC%BC%ED%95%9C_%EC%9E%AC%EC%9D%80%EC%94%A8%EC%9D%98_Swift_%EB%AC%B8%EB%B2%95%ED%8E%B8/README.md)
